version: '1.0.0-alpha{build}'
image: Visual Studio 2017
shallow_clone: true
configuration: Release
install:
  - nuget sources add -Name ReactiveUIBeta -Source https://www.myget.org/F/reactiveui/api/v3/index.json
before_build:
  - nuget restore
build:
  project: ReactiveUI.Routing.sln
  publish_nuget: true
test:
  assemblies:
    - '**\*.Tests.dll'
nuget:
  project_feed: true
artifacts:
  - path: 'src\**\*.nupkg'
assembly_info:
  patch: true
  file: '**\AssemblyInfo.cs'
  assembly_version: '1.0.0.0'
  assembly_file_version: '1.0.0.0'
  assembly_informational_version: $(appveyor_build_version)