version: '1.0.0-alpha{build}'
image: Visual Studio 2015
shallow_clone: true
configuration: Release
before_build:
  - nuget restore
build:
  project: ReactiveUI.Routing.sln
  publish_nuget: true
test:
  assemblies:
    - '**\*.Tests.dll'
nuget:
  project_feed: true
artifacts:
  - path: 'src\**\*.nupkg'
assembly_info:
  patch: true
  file: 'src\ReactiveUI.Routing\Properties\AssemblyInfo.cs'
  assembly_version: '1.0.0.0'
  assembly_file_version: '1.0.0.0'
  assembly_informational_version: $(appveyor_build_version)