version: '1.0.0-alpha{build}'
image: Visual Studio 2015
shallow_clone: true

configuration: Release

before_build:
  - nuget restore

build:
  project: ReactiveUI.Routing.sln

test:
  assemblies:
    - '**\*.Tests.dll'